package io.github.nishadchayanakhawa.testestimatehub.repositories;

//import section
//jpa
import org.springframework.data.jpa.repository.JpaRepository;

import io.github.nishadchayanakhawa.testestimatehub.model.Release;

/**
 * <b>Class Name</b>: ReleaseRepository<br>
 * <b>Description</b>: JPA repository for Release records<br>
 * 
 * @author nishad.chayanakhawa
 */
public interface ReleaseRepository extends JpaRepository<Release, Long> {
	// Functions will be auto generated by JPA
}
